import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.scss";
import { checkIsMobile } from "@/lib/isMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = checkIsMobile();
  const deviceClass = isMobile ? "mobile" : "laptop";
  return (
    <html lang="en" className={deviceClass}>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
