import type { Metadata } from "next";
import "@/app/globals.scss";
import Header from "@/components/top/Header";
import { DeviceProvider } from "@/contexts/DeviceContext";
import { checkIsMobile } from "@/lib/isMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isMobile = checkIsMobile(); // 2. 判定はここで一度だけ！
  const deviceClass = isMobile ? "mobile" : "laptop";

  return (
    <html lang="ja" className={deviceClass}>
      <head>
        {/* ↓ ここにAdobe Fontsのコードを追加 */}
        <link rel="stylesheet" href="https://use.typekit.net/dvm8phe.css" />
      </head>
      <body>
        <Header />
        {/* 3. isMobileの結果をセットして、アプリ全体（children）を囲む */}
        <DeviceProvider isMobile={isMobile}>
          {/* ここにHeaderやFooterなどを配置できます */}
          {children}
        </DeviceProvider>
      </body>
    </html>
  );
}
